from enum import Enum


class OWSkin(Enum):
    """ 可选守望先锋皮肤，插件会针对选中相应皮肤做出操作 """
    SHARED = 'SHARED'
    ANA_CLASSIC = 'ANA_CLASSIC'
    MERCY_CLASSIC = 'MERCY_CLASSIC'
    VENTURE_OVERWATCH2 = 'VENTURE_OVERWATCH2'
    KIRIKO_OVERWATCH2 = 'KIRIKO_OVERWATCH2'
    GENJI_CLASSIC = 'GENJI_CLASSIC'
    TRACER_OVERWATCH2 = 'TRACER_OVERWATCH2'
