from ....shared.models.rigging.human import Human, HumanPart

base_deform = {
    "bone_0011": Human(part=HumanPart.HEAD),
    "bone_0010": Human(part=HumanPart.NECK),
    "bone_000F": Human(part=HumanPart.CHEST),
    "bone_0052": Human(part=HumanPart.SPINE, index=1),
    "bone_0051": Human(part=HumanPart.SPINE, index=2),
    "bone_0054": Human(part=HumanPart.HIPS),
    "bone_0034": Human(part=HumanPart.SHOULDER, side="L"),
    "bone_000C": Human(part=HumanPart.SHOULDER, side="R"),
    "bone_0031": Human(part=HumanPart.UPPER_ARM, index=1, side="L"),
    "bone_0032": Human(part=HumanPart.UPPER_ARM, index=2, side="L"),
    "bone_004F": Human(part=HumanPart.UPPER_ARM, index=3, side="L"),
    "bone_004D": Human(part=HumanPart.UPPER_ARM, index=1, side="R"),
    "bone_004E": Human(part=HumanPart.UPPER_ARM, index=2, side="R"),
    "bone_0033": Human(part=HumanPart.UPPER_ARM, index=3, side="R"),
    "bone_001A": Human(part=HumanPart.FOREARM, index=1, side="L"),
    "bone_001B": Human(part=HumanPart.FOREARM, index=2, side="L"),
    "bone_0030": Human(part=HumanPart.FOREARM, index=3, side="L"),
    "bone_0038": Human(part=HumanPart.FOREARM, index=1, side="R"),
    "bone_0039": Human(part=HumanPart.FOREARM, index=2, side="R"),
    "bone_004C": Human(part=HumanPart.FOREARM, index=3, side="R"),  # WristTwist_R
    "bone_001C": Human(part=HumanPart.WRIST, side="L"),
    "bone_003A": Human(part=HumanPart.WRIST, side="R"),
    "bone_002A": Human(part=HumanPart.FINGER_THUMB, index=1, side="L"),
    "bone_002B": Human(part=HumanPart.FINGER_THUMB, index=2, side="L"),
    "bone_0048": Human(part=HumanPart.FINGER_THUMB, index=1, side="R"),
    "bone_0049": Human(part=HumanPart.FINGER_THUMB, index=2, side="R"),
    "bone_001D": Human(part=HumanPart.FINGER_INDEX, index=1, side="L"),
    "bone_001E": Human(part=HumanPart.FINGER_INDEX, index=2, side="L"),
    "bone_001F": Human(part=HumanPart.FINGER_INDEX, index=3, side="L"),
    "bone_003B": Human(part=HumanPart.FINGER_INDEX, index=1, side="R"),
    "bone_003C": Human(part=HumanPart.FINGER_INDEX, index=2, side="R"),
    "bone_003D": Human(part=HumanPart.FINGER_INDEX, index=3, side="R"),
    "bone_0020": Human(part=HumanPart.FINGER_MIDDLE, index=1, side="L"),
    "bone_0021": Human(part=HumanPart.FINGER_MIDDLE, index=2, side="L"),
    "bone_0022": Human(part=HumanPart.FINGER_MIDDLE, index=3, side="L"),
    "bone_003E": Human(part=HumanPart.FINGER_MIDDLE, index=1, side="R"),
    "bone_003F": Human(part=HumanPart.FINGER_MIDDLE, index=2, side="R"),
    "bone_0040": Human(part=HumanPart.FINGER_MIDDLE, index=3, side="R"),
    "bone_0026": Human(part=HumanPart.FINGER_RING, index=1, side="L"),
    "bone_0027": Human(part=HumanPart.FINGER_RING, index=2, side="L"),
    "bone_0028": Human(part=HumanPart.FINGER_RING, index=3, side="L"),
    "bone_0044": Human(part=HumanPart.FINGER_RING, index=1, side="R"),
    "bone_0045": Human(part=HumanPart.FINGER_RING, index=2, side="R"),
    "bone_0046": Human(part=HumanPart.FINGER_RING, index=3, side="R"),
    "bone_0023": Human(part=HumanPart.FINGER_PINKY, index=1, side="L"),
    "bone_0024": Human(part=HumanPart.FINGER_PINKY, index=2, side="L"),
    "bone_0025": Human(part=HumanPart.FINGER_PINKY, index=3, side="L"),
    "bone_0041": Human(part=HumanPart.FINGER_PINKY, index=1, side="R"),
    "bone_0042": Human(part=HumanPart.FINGER_PINKY, index=2, side="R"),
    "bone_0043": Human(part=HumanPart.FINGER_PINKY, index=3, side="R"),
    "bone_0029": Human(part=HumanPart.FINGER_THUMB_CARPAL, side="L"),
    "bone_0835": Human(part=HumanPart.FINGER_INDEX_CARPAL, side="L"),
    "bone_0837": Human(part=HumanPart.FINGER_MIDDLE_CARPAL, side="L"),
    "bone_0839": Human(part=HumanPart.FINGER_RING_CARPAL, side="L"),
    "bone_00E0": Human(part=HumanPart.FINGER_PINKY_CARPAL, side="L"),
    "bone_0047": Human(part=HumanPart.FINGER_THUMB_CARPAL, side="R"),
    "bone_0836": Human(part=HumanPart.FINGER_INDEX_CARPAL, side="R"),
    "bone_0838": Human(part=HumanPart.FINGER_MIDDLE_CARPAL, side="R"),
    "bone_083A": Human(part=HumanPart.FINGER_RING_CARPAL, side="R"),
    "bone_00E1": Human(part=HumanPart.FINGER_PINKY_CARPAL, side="R"),
    "bone_0056": Human(part=HumanPart.THIGH, index=1, side="L"),
    "bone_0057": Human(part=HumanPart.THIGH, index=2, side="L"),
    "bone_0058": Human(part=HumanPart.THIGH, index=3, side="L"),
    "bone_0060": Human(part=HumanPart.THIGH, index=1, side="R"),
    "bone_0061": Human(part=HumanPart.THIGH, index=2, side="R"),
    "bone_0062": Human(part=HumanPart.THIGH, index=3, side="R"),
    "bone_005C": Human(part=HumanPart.KNEE, index=1, side="L"),
    "bone_005D": Human(part=HumanPart.KNEE, index=2, side="L"),
    "bone_005E": Human(part=HumanPart.KNEE, index=3, side="L"),
    "bone_0066": Human(part=HumanPart.KNEE, index=1, side="R"),
    "bone_0067": Human(part=HumanPart.KNEE, index=2, side="R"),
    "bone_0068": Human(part=HumanPart.KNEE, index=3, side="R"),
    "bone_005A": Human(part=HumanPart.FOOT, side="L"),
    "bone_0064": Human(part=HumanPart.FOOT, side="R"),
    "bone_005B": Human(part=HumanPart.TOES, side="L"),
    "bone_0065": Human(part=HumanPart.TOES, side="R"),
}

other_deform = {
    "bone_08D5": Human(base_name="pupil", side="L"),
    "bone_0012": Human(base_name="head_top"),
}

no_deform = {
    "bone_0000": Human(base_name="root"),
    "bone_0001": Human(base_name="root", index=1),
    "bone_0059": Human(base_name="knee", side="L"),
    "bone_0063": Human(base_name="knee", side="R"),
    "bone_0055": Human(base_name="thigh", side="L"),
    "bone_005F": Human(base_name="thigh", side="R"),
    "bone_0397": Human(base_name="eyelid_upper", side="L"),
    "bone_0396": Human(base_name="eyelid_lower", side="L"),
    "bone_0399": Human(base_name="eyelid_upper", side="R"),
    "bone_0398": Human(base_name="eyelid_lower", side="R"),
    "bone_00C1": Human(base_name="heel", side="L"),
    "bone_00C2": Human(base_name="heel", side="R"),
    "bone_0005": Human(base_name="chest"),
    "bone_0003": Human(base_name="spine", index=1),
    "bone_0004": Human(base_name="spine", index=2),
    "bone_0053": Human(base_name="hips"),
    "bone_000B": Human(base_name="lower_face"),
    "bone_0050": Human(base_name="shoulder", side="L"),
    "bone_0035": Human(base_name="shoulder", side="R"),
    "bone_000D": Human(base_name="upper_arm", side="L"),
    "bone_0036": Human(base_name="upper_arm", side="R"),
    "bone_000E": Human(base_name="forearm", side="L"),  # 也许是 elbow
    "bone_0037": Human(base_name="forearm", side="R"),  # 也许是 elbow
    "bone_0002": Human(base_name="pelvis"),
}

face_deform = {
    "bone_0015": Human(part=HumanPart.EYEBROW, index=1, side="R"),
    "bone_0014": Human(part=HumanPart.EYEBROW, index=2, side="R"),
    "bone_0013": Human(part=HumanPart.EYEBROW, index=3, side="R"),
    "bone_0384": Human(part=HumanPart.EYEBROW, index=4, side="R"),
    "bone_0017": Human(part=HumanPart.EYEBROW, index=1, side="L"),
    "bone_0018": Human(part=HumanPart.EYEBROW, index=2, side="L"),
    "bone_0019": Human(part=HumanPart.EYEBROW, index=3, side="L"),
    "bone_0385": Human(part=HumanPart.EYEBROW, index=4, side="L"),
    "bone_0016": Human(part=HumanPart.EYEBROW, position="middle"),
    "bone_038A": Human(part=HumanPart.EYELID, position="upper", index=1, side="L"),
    "bone_038C": Human(part=HumanPart.EYELID, position="upper", index=3, side="L"),
    "bone_038B": Human(part=HumanPart.EYELID, position="upper", index=2, side="L"),
    "bone_038D": Human(part=HumanPart.EYELID, position="lower", index=1, side="L"),
    "bone_038E": Human(part=HumanPart.EYELID, position="lower", index=2, side="L"),
    "bone_038F": Human(part=HumanPart.EYELID, position="lower", index=3, side="L"),
    "bone_0393": Human(part=HumanPart.EYELID, position="upper", index=1, side="R"),
    "bone_0394": Human(part=HumanPart.EYELID, position="upper", index=2, side="R"),
    "bone_0395": Human(part=HumanPart.EYELID, position="upper", index=3, side="R"),
    "bone_0391": Human(part=HumanPart.EYELID, position="lower", index=1, side="R"),
    "bone_0390": Human(part=HumanPart.EYELID, position="lower", index=2, side="R"),
    "bone_0392": Human(part=HumanPart.EYELID, position="lower", index=3, side="R"),
    "bone_0006": Human(part=HumanPart.EYELID, position="inner", side="L"),
    "bone_0007": Human(part=HumanPart.EYELID, position="outer", side="L"),
    "bone_0387": Human(part=HumanPart.EYELID, position="inner", side="R"),
    "bone_0386": Human(part=HumanPart.EYELID, position="outer", side="R"),
    "bone_0608": Human(part=HumanPart.CHEEK_UPPER, position="inner", side="L"),
    "bone_060A": Human(part=HumanPart.CHEEK_UPPER, position="middle", side="L"),
    "bone_03A2": Human(part=HumanPart.CHEEK_UPPER, position="outer", side="L"),
    "bone_0609": Human(part=HumanPart.CHEEK_UPPER, position="inner", side="R"),
    "bone_03A3": Human(part=HumanPart.CHEEK_UPPER, position="middle", side="R"),
    "bone_060B": Human(part=HumanPart.CHEEK_UPPER, position="outer", side="R"),
    "bone_03A4": Human(part=HumanPart.CHEEK, position="inner", side="L"),
    "bone_039E": Human(part=HumanPart.CHEEK, position="middle", side="L"),
    "bone_071D": Human(part=HumanPart.CHEEK, position="outer", side="L"),
    "bone_03A5": Human(part=HumanPart.CHEEK, position="inner", side="R"),
    "bone_039F": Human(part=HumanPart.CHEEK, position="middle", side="R"),
    "bone_071E": Human(part=HumanPart.CHEEK, position="outer", side="R"),
    "bone_060C": Human(part=HumanPart.CHEEK_LOWER, position="inner", side="L"),
    "bone_03A6": Human(part=HumanPart.CHEEK_LOWER, position="middle", side="L"),
    "bone_03A0": Human(part=HumanPart.CHEEK_LOWER, position="outer", side="L"),
    "bone_060D": Human(part=HumanPart.CHEEK_LOWER, position="inner", side="R"),
    "bone_03A7": Human(part=HumanPart.CHEEK_LOWER, position="middle", side="R"),
    "bone_03A1": Human(part=HumanPart.CHEEK_LOWER, position="outer", side="R"),
    "bone_0009": Human(part=HumanPart.NOSE, side="L"),
    "bone_000A": Human(part=HumanPart.NOSE, side="R"),
    "bone_0008": Human(part=HumanPart.NOSE, position="tip"),
    "bone_0388": Human(part=HumanPart.NOSE_BRIEGE, side="L"),
    "bone_0389": Human(part=HumanPart.NOSE_BRIEGE, side="R"),
    "bone_03AA": Human(part=HumanPart.LIP_UPPER, position="middle"),
    "bone_03AB": Human(part=HumanPart.LIP_LOWER, position="middle"),
    "bone_03B0": Human(part=HumanPart.LIP, position="corner", side="L"),
    "bone_03B3": Human(part=HumanPart.LIP, position="corner", side="R"),
    "bone_03A9": Human(part=HumanPart.LIP_UPPER, index=1, side="L"),
    "bone_03A8": Human(part=HumanPart.LIP_UPPER, index=2, side="L"),
    "bone_03B4": Human(part=HumanPart.LIP_UPPER, index=1, side="R"),
    "bone_03B5": Human(part=HumanPart.LIP_UPPER, index=2, side="R"),
    "bone_03AC": Human(part=HumanPart.LIP_LOWER, index=1, side="L"),
    "bone_03AF": Human(part=HumanPart.LIP_LOWER, index=2, side="L"),
    "bone_03B1": Human(part=HumanPart.LIP_LOWER, index=1, side="R"),
    "bone_03B2": Human(part=HumanPart.LIP_LOWER, index=2, side="R"),
    "bone_03AD": Human(part=HumanPart.CHIN, position="outer", side="L"),
    "bone_03AE": Human(part=HumanPart.CHIN, position="outer", side="R"),
    "bone_03B6": Human(part=HumanPart.CHIN, position="middle"),
    "bone_03BC": Human(part=HumanPart.JAW),
    "bone_039A": Human(part=HumanPart.EYE, side="L"),
    "bone_039B": Human(part=HumanPart.EYE, side="R"),
    "bone_03B7": Human(part=HumanPart.TEETH, position="upper"),
    "bone_03B8": Human(part=HumanPart.TEETH, position="lower"),
    "bone_03BB": Human(part=HumanPart.TONGUE, index=1),
    "bone_03BA": Human(part=HumanPart.TONGUE, index=2),
    "bone_03B9": Human(part=HumanPart.TONGUE, index=3),
}
